[package]
name = "rust_snake"
version = "0.1.0"
authors = ["Donovan Allen <me@donovanallen.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ncurses = "5.99.0"
